<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Sidequest_Web-c0a01f43-25b9-411b-8761-85c1fe8517de</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.14.4" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.14.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" PrivateAssets="all" />
    <ProjectReference Include="..\Sidequest.Application\Sidequest.Application.csproj" />
    <ProjectReference Include="..\Sidequest.Infrastructure\Sidequest.Infrastructure.csproj" />
  </ItemGroup>

</Project>
